name: Check PR Template

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check PR Template
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the PR body
          PR_BODY=$(jq -r .pull_request.body "$GITHUB_EVENT_PATH")

          # Check if the checkbox is checked
          if [[ "$PR_BODY" =~ "- \[x\]" ]]; then
            echo "Checkbox is checked. PR can be merged."
          else
            echo "Checkbox is not checked. Please check the box in the PR template."
            exit 1
          fi
