name: Enforce PR Checklist
on:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  check-pr-template:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR body for checked box
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          # Print PR body for debugging (optional)
          echo "PR_BODY: $PR_BODY"
          # Require at least one checked box in the checklist
          if ! grep -iE -- "- \[[xX]\]" <<< "$PR_BODY"; then
            echo "You must check at least one box in the PR template checklist."
            exit 1
          fi
