name: Check PR Template

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate_pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check PR Template
        uses: ./.github/pull_request_template.md
        with:
          template_path: "./.github/pull_request_template.md"
          pr_description: ${{ github.event.pull_request.body }}
