name: Check PR Template

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  check-template:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
      - uses: actions/checkout@v2

      - name: Check PR Template
        uses: ./pull_request_template.md
        with:
          template_path: "././pull_request_template.md"
          pr_description: ${{ github.event.pull_request.body }}
